[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/customs
admin_passwd = biva_admin_2024
db_host = biva_db
db_port = 5432
db_user = biva_odoo
db_password = biva_odoo_2024
db_name = biva_postgres
limit_time_cpu = 1200
limit_time_real = 1800
dbfilter = ^biva.*$
logfile = /var/log/odoo/odoo.log
log_level = info 