{
    "name": "SurePay HR Employee Management",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "summary": "Comprehensive HR management with contact expiration notifications, skill gap analysis, and disciplinary actions",
    "author": "SurePay Ltd",
    "website": "https://surepayltd.com",
    "license": "LGPL-3",
    "depends": ["base", "hr", "hr_skills", "hr_contract", "mail", "web"],
    'data': [
        'data/skill_level_data.xml',
        'security/ir.model.access.csv',
        'security/security_groups.xml',
        'security/hr_skill_gap_security.xml',
        'data/mail_templates.xml',
        'data/cron_jobs.xml',
        'views/hr_employee_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_disciplinary_action_views.xml',
        'views/hr_skill_views.xml',
        'views/hr_skill_gap_views.xml',
        'views/hr_skill_gap_menu.xml',
        'views/hr_analytics_views.xml',
        'views/menus.xml',
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "external_dependencies": {"python": [], "bin": []},
}
